// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTVtMbLncactnhoWVDjReM5NBnWUZq5QQ',
    appId: '1:947659976170:web:508a880b55c95827f65693',
    messagingSenderId: '947659976170',
    projectId: 'fasum-app-847df',
    authDomain: 'fasum-app-847df.firebaseapp.com',
    storageBucket: 'fasum-app-847df.firebasestorage.app',
    measurementId: 'G-MX8H0LZK99',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMyEkcNnrifqzLU2Sj72PIAFMcrfIIuuc',
    appId: '1:947659976170:android:c833e4542ce6350ff65693',
    messagingSenderId: '947659976170',
    projectId: 'fasum-app-847df',
    storageBucket: 'fasum-app-847df.firebasestorage.app',
  );
}
